export const ENV = {
  get appId() { return process.env.VITE_APP_ID ?? ""; },
  get cookieSecret() { return process.env.JWT_SECRET ?? ""; },
  get databaseUrl() { return process.env.DATABASE_URL ?? ""; },
  get oAuthServerUrl() { return process.env.OAUTH_SERVER_URL ?? ""; },
  get ownerId() { return process.env.OWNER_OPEN_ID ?? ""; },
  get isProduction() { return process.env.NODE_ENV === "production"; },
  get forgeApiUrl() { return process.env.BUILT_IN_FORGE_API_URL ?? ""; },
  get forgeApiKey() { return process.env.BUILT_IN_FORGE_API_KEY ?? ""; },
  get eodhdApiKey() { return process.env.EODHD_API_KEY ?? ""; },
  get stripeSecretKey() { return process.env.STRIPE_SECRET_KEY ?? ""; },
  get stripeWebhookSecret() { return process.env.STRIPE_WEBHOOK_SECRET ?? ""; },
  get finnhubApiKey() { return process.env.FINNHUB_API_KEY ?? ""; },
  get fiscalApiKey() { return process.env.FISCAL_API_KEY ?? ""; },
  get resendApiKey() { return process.env.RESEND_API_KEY ?? ""; },
  get twilioAccountSid() { return process.env.TWILIO_ACCOUNT_SID ?? ""; },
  get twilioAuthToken() { return process.env.TWILIO_AUTH_TOKEN ?? ""; },
  get twilioWhatsappNumber() { return process.env.TWILIO_WHATSAPP_NUMBER ?? ""; },
  get emailFrom() { return process.env.EMAIL_FROM ?? ""; },
  get ownerName() { return process.env.OWNER_NAME ?? ""; },
};
